# Generated by Django 5.1.15 on 2026-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leaddocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leadnote',
            name='created_by',
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='modified_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
