# Generated by Django 5.1.15 on 2026-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='profile',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='created_by_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
