# Generated by Django 5.1.15 on 2026-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_alter_project_manager_alter_project_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, help_text='Unique project code/reference number', max_length=50, unique=True),
        ),
    ]
