# Generated by Django 5.1.15 on 2026-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='purchasecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasecategory',
            name='profile',
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
