# Generated by Django 5.1.15 on 2026-02-15 08:16

from django.db import migrations, models


def populate_client_ids(apps, schema_editor):
    """Populate client_id for existing clients"""
    Client = apps.get_model('clients', 'Client')
    clients = Client.objects.all().order_by('id')
    
    for index, client in enumerate(clients, start=1):
        client.client_id = f"CL-{index:06d}"
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        # Step 2: Populate existing records
        migrations.RunPython(populate_client_ids, reverse_code=migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
