# Generated by Django 5.1.15 on 2026-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='initials',
            field=models.CharField(blank=True, help_text='2-5 characters', max_length=10, verbose_name='Client Initials'),
        ),
    ]
