# Generated by Django 5.1.7 on 2025-08-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('project_management', '0003_alter_project_manager_alter_project_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banking_accounts', to='project_management.project'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_debts', to='project_management.project'),
        ),
        migrations.AlterField(
            model_name='projectfinancialsummary',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='project_management.project'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_taxes', to='project_management.project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_transactions', to='project_management.project'),
        ),
    ]
