# Generated by Django 5.1.15 on 2026-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_account_project_alter_debt_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.AddField(
            model_name='account',
            name='owner_id',
            field=models.IntegerField(default=1),
        ),
    ]
