# Generated by Django 5.1.15 on 2026-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_account_owner_account_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_bank_account_id',
            field=models.IntegerField(blank=True, help_text='Reference to CompanyBankAccount', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, help_text='4-digit PIN for transactions (optional)', max_length=4, null=True),
        ),
    ]
