# Generated by Django 5.1.15 on 2026-02-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_account_company_bank_account_id_alter_account_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pin',
        ),
    ]
