# Generated by Django 5.1.15 on 2026-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_client_alter_document_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='apply_vat',
            field=models.BooleanField(default=True, verbose_name='Apply VAT'),
        ),
        migrations.AddField(
            model_name='quote',
            name='apply_vat',
            field=models.BooleanField(default=True, verbose_name='Apply VAT'),
        ),
    ]
