# Generated by Django 5.1.15 on 2026-02-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_apply_vat_quote_apply_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
