# Generated by Django 5.1.15 on 2026-02-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_edit_count_quote_edit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='document',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID who created this document', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID who last updated this document', null=True),
        ),
    ]
