# Generated by Django 5.1.15 on 2026-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='apply_vat',
            field=models.BooleanField(default=False, verbose_name='Apply VAT'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('INVOICED', 'Invoiced')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='apply_vat',
            field=models.BooleanField(default=False, verbose_name='Apply VAT'),
        ),
    ]
