# Generated by Django 5.1.15 on 2026-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_apply_vat_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='apply_vat',
            field=models.BooleanField(default=True, verbose_name='Apply VAT'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='apply_vat',
            field=models.BooleanField(default=True, verbose_name='Apply VAT'),
        ),
    ]
