# Generated by Django 5.1.10 on 2025-08-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_companyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('business', 'Business Account'), ('current', 'Current Account'), ('fixed_deposit', 'Fixed Deposit'), ('other', 'Other')], default='business', max_length=20, verbose_name='Account Type')),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='SWIFT/BIC Code')),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch Name')),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Branch Code')),
                ('routing_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Routing Number')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Account')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='registration.company')),
            ],
            options={
                'verbose_name': 'Company Bank Account',
                'verbose_name_plural': 'Company Bank Accounts',
                'unique_together': {('company', 'account_number', 'bank_name')},
            },
        ),
    ]
