# Generated by Django 5.1.15 on 2026-02-14 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_companybankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('clients', 'Clients Management'), ('leads', 'Leads Management'), ('sales', 'Sales Management'), ('projects', 'Project Management'), ('documents', 'Document Management'), ('expenses', 'Expense Tracking'), ('purchases', 'Purchase Management'), ('banking', 'Banking & Finance'), ('reports', 'Reports & Analytics'), ('people', 'People Management'), ('communication', 'Communication'), ('dashboard', 'Dashboard')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-puzzle-piece', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_subscription', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Module',
                'verbose_name_plural': 'App Modules',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('app_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='registration.appmodule')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_apps', to='registration.company')),
                ('enabled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_company_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company App',
                'verbose_name_plural': 'Company Apps',
                'ordering': ['app_module__order', 'app_module__display_name'],
                'unique_together': {('company', 'app_module')},
            },
        ),
    ]
