# Generated by Django 5.1.15 on 2026-02-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_appmodule_companyapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='initials',
            field=models.CharField(blank=True, help_text='2-5 characters (e.g., CC, ABC)', max_length=10, verbose_name='Company Initials'),
        ),
    ]
