# Generated by Django 5.1.10 on 2025-08-06 16:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_emailaccount_provider_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('session_string', models.TextField(blank=True, null=True)),
                ('api_id', models.CharField(blank=True, max_length=20, null=True)),
                ('api_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('auto_sync_messages', models.BooleanField(default=True)),
                ('auto_sync_contacts', models.BooleanField(default=True)),
                ('sync_frequency', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Session',
                'verbose_name_plural': 'Telegram Sessions',
            },
        ),
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ['-sent_at', '-created_at'], 'verbose_name': 'Telegram Message', 'verbose_name_plural': 'Telegram Messages'},
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='forward_from_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='forward_from_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='is_outgoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('voice', 'Voice Message'), ('sticker', 'Sticker'), ('animation', 'Animation/GIF'), ('location', 'Location'), ('contact', 'Contact'), ('poll', 'Poll'), ('venue', 'Venue')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='reply_to_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='telegram_media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'mp4', 'mp3', 'ogg', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='telegrammessage',
            unique_together={('telegram_message_id', 'telegram_chat_id')},
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('allowed_updates', models.JSONField(blank=True, default=list)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_messages_received', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel'), ('bot', 'Bot')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('unread_count', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='telegram_chat_photos/')),
                ('last_message_date', models.DateTimeField(blank=True, null=True)),
                ('last_read_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Chat',
                'verbose_name_plural': 'Telegram Chats',
                'ordering': ['-last_message_date'],
            },
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.telegramchat'),
        ),
        migrations.CreateModel(
            name='TelegramContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_contact', models.BooleanField(default=False)),
                ('is_mutual_contact', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='telegram_profiles/')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Contact',
                'verbose_name_plural': 'Telegram Contacts',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='communication.telegramcontact'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.telegramcontact'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['telegram_chat_id', '-sent_at'], name='communicati_telegra_0f5eef_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['user', 'status'], name='communicati_user_id_5e6aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['is_outgoing', 'chat'], name='communicati_is_outg_7b32ab_idx'),
        ),
        migrations.AddField(
            model_name='telegramsession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='telegrambot',
            unique_together={('user', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='telegramchat',
            unique_together={('user', 'telegram_chat_id')},
        ),
    ]
