# Generated by Django 5.1.15 on 2026-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='registered_by',
        ),
        migrations.AddField(
            model_name='person',
            name='registered_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
