# Generated by Django 5.1.15 on 2026-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacthistory',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='contacthistory',
            name='sent_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
