# Generated by Django 5.1.7 on 2025-08-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_supplier_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
