# Generated by Django 5.1.7 on 2025-08-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20250801_1545'),
    ]

    operations = [
    ]
