# Generated by Django 5.1.15 on 2026-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_options_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
    ]
